### ISSUE TITLE
undefined reference to `operator delete(void*, unsigned int)'

### ISSUE THREAD

**Issue by asiawin** [Remco123/CactusOS#3]
When I compile CactusOS, I get this error: `undefined reference to 'operator delete(void*, unsigned int)'`

Did you forgot to implement C++ runtime functions or is this any linkage error?

**Comment by Remco123** [comment]
Hey Asiawin,

Are you using the correct cross compiler for compiling? The compiler you should be using is i686-elf-gcc, see: https://wiki.osdev.org/GCC_Cross-Compiler for details. I have implemented the basic runtime functions for memory management so it should compile just fine. Please let me know if this helped.

Greetings Remco

**Comment by asiawin** [comment]
Yes. I'm using a cross compiler. I have `i686-elf` gcc, Binutils and gdb. But I don't have a C++ cross compiler so I'm using the gcc that came with my WSL ubuntu. I havey own OS called [Cadex OS](http://github.com/CadexOS/Cadex-OS-Official/) and I'm using my native GCC to build the C++ programs on it and I never faced an issue with it. It also has C++ Runtime libraries like CactusOS 🌵

**Comment by Remco123** [comment]
After following the instructions for a cross-compiler on the osdev wiki you should also get a c++ version. Perhaps you downloaded a pre-compiled version? The programs are not meant to be compiled using the default gcc but I can see if I can make this possible. Hope this is useful.

**Comment by asiawin** [comment]
No. I made cadex os from a project called basekernel. I used the cross compiler script that was in that project.

**Comment by asiawin** [comment]
Oh now I remember, it had `--enable-langauges=c` flag for the GCC configure script. That's why I didn't get a C++ compiler

**Comment by asiawin** [comment]
I fixed the problem from changing `void operator delete(void* ptr, unsigned long size)` to `void operator delete(void* ptr, unsigned int size)` and all functions like that, and the build succeeded.

**Comment by Remco123** [comment]
Okay cool! I now changed the unsigned long to size_t so it will automatically be the correct format for each architecture. Thanks for pointing this out.
